# Github Action to look at a URL, parse the JSON, and if any of the keys are true, send an email to the specified email address. Ideally this uses github script or something with javascript. Also the email can use the send mail action.

name: Notify if appointment exists

on:
  schedule:
    - cron: "0 0 * * *"
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check if appointment exists
        id: appointment-result
        uses: actions/github-script@v7
        with:
          script: |
            // This will look for appointments this month and the two months after
            for (let i = 0; i < 3; i++) {
              const today = new Date();
              const date = new Date(today.setMonth(today.getMonth() + i));
              console.log('Checking for appointments in ' + date.getFullYear() + '-' + (date.getMonth() + 1));

              const url = `https://charlestonanimalsocietytvarprogram.as.me/api/scheduling/v1/availability/month?owner=ef088d93&appointmentTypeId=61661387&calendarId=10515025&timezone=America%2FNew_York&month=${date.getFullYear()}-${date.getMonth() + 1}-01`;

              const response = await fetch(url);
              const data = await response.json();
              const keys = Object.keys(data);
              if (keys.some(key => data[key] === true)) {
                console.log('Found an appointment!');
                return 'false';
              }
              console.log('No appointments found');
            }
          result-encoding: string

      - name: Send email
        if: ${{ steps.appointment-result.outputs.result == 'true' }}
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          # Literal body:
          body: |
            There is an appointment available at Charleston Animal Society to get your the stray cats fixed.
            Go to https://charlestonanimalsocietytvarprogram.as.me to book it.
          to: joshua.bremer@gmail.com
          from: Joshua Bremer
